name: Manual Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Push to system
        uses: dokku/github-action@master
        with:
          branch: main
          git_push_flags: '--force'
          git_remote_url: 'ssh://dokku@common.uzbekvoice.ai:2003/bot'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}